"""add user relation to transactions

Revision ID: 5897a88e0c77
Revises: 72b95e297c94
Create Date: 2026-05-15 13:20:09.059140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5897a88e0c77'
down_revision: Union[str, Sequence[str], None] = '72b95e297c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('transactions', 'type',
               existing_type=postgresql.ENUM('entrada', 'saida', name='transactiontype'),
               type_=postgresql.ENUM('entrada', 'saida', name='transaction_type'),
               existing_nullable=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_hashed_password_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_hashed_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'type',
               existing_type=postgresql.ENUM('entrada', 'saida', name='transaction_type'),
               type_=postgresql.ENUM('entrada', 'saida', name='transactiontype'),
               existing_nullable=False)
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
